CUDA_VISIBLE_DEVICES=1 python main.py \
    --mode='fine'\
    --train_file="../data/simmc2_disambiguate_dstc10_train.json" \
    --dev_file="../data/simmc2_disambiguate_dstc10_dev.json" \
    --devtest_file="../data/simmc2_disambiguate_dstc10_devtest.json" \
    --model="roberta-large"\
    --seed=42\
    --batch_size=6\
    --learning_rate=2e-5\
    --train\
    --eval\